#app
server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-threads: 1000
    max-connections: 1000
  servlet:
    session:
      timeout: 10ms
#spring
spring:
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**